---
- name: Create a directory for configuration files.
  file:
    path: '{{ backup_dir.rstrip("/") }}/{{ now }}/conf/'
    group: root
    mode: 0755
    owner: root
    state: directory

- name: Copy configuration files from conf.d.
  shell: rsync --exclude=conf.d/postgres.py --exclude=conf.d/mongo.py --exclude=conf.d/celeryd.py -auq /etc/tower/ {{ backup_dir.rstrip("/") }}/{{ now }}/conf/
