---
pg_run_dir: '/var/run/postgresql'
pg_conf_dir: "/var/lib/pgsql/9.4/data'
pg_conf_location: '{{ pg_conf_dir }}/postgresql.conf'
pg_hba_location: '{{ pg_conf_dir }}/pg_hba.conf'
pg_init_name: 'postgresql'
